from reproducibility.plot.plotter import Plotter


class Section3_BERTonSTILTs_5k(Plotter):
    def __init__(self):
        super().__init__()
        self.subplots = (3, 3)
        self.figsize = (20, 20)
        self.save_path = f"{self.root}/figures/section3_bert_on_stilts_5k.pdf"
        self.config = {
            f"{self.root}/cola_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "CoLA",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/mrpc_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "MRPC",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/rte_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "RTE",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/stsb_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "STS",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/mnli_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "MNLI",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/qnli_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "QNLI",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/qqp_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "QQP",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/sst2_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "SST2",
                "xlim": [1, 20],
                "fontsize": 24
            },
            f"{self.root}/wnli_5k_search.tsv": {
                "linestyle": "-",
                "logx": True,
                "performance_metric": "accuracy",
                'duration_field': 'training_duration',
                'dataset_size_field': 'dataset_reader.sample',
                'dev_performance_field': 'best_validation_accuracy',
                'model_field': 'model.encoder.architecture.type',
                'sep': '\t',
                'lr_field': 'trainer.optimizer.lr',
                "encoder_name": None,
                "plot_errorbar": False,
                "legend_loc": 'lower right',
                "x_axis_time": False,
                "linewidth": 3,
                "relabel_logx_scalar": [5, 10, 15],
                "data_name": "WNLI",
                "xlim": [1, 20],
                "fontsize": 24
            }
        }

if __name__ == "__main__":
    bert_on_stilts = Section3_BERTonSTILTs_5k()
    bert_on_stilts.plot()