from environments.suchin_environments import SUCHIN_ENVIRONMENTS
from environments.eric_environments import ERIC_ENVIRONMENTS

_SUCHIN_ENVIRONMENTS = {}
_ERIC_ENVIRONMENTS = {}

for key in SUCHIN_ENVIRONMENTS:
    _SUCHIN_ENVIRONMENTS["SUCHIN_" + key] = SUCHIN_ENVIRONMENTS[key]

for key in ERIC_ENVIRONMENTS:
    _ERIC_ENVIRONMENTS["ERIC_" + key] = ERIC_ENVIRONMENTS[key]

ENVIRONMENTS = {**_SUCHIN_ENVIRONMENTS, **_ERIC_ENVIRONMENTS}
